config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get '/home/about' => 'books#about'
  get  root "users#top"
  devise_for :users
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only:[:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update,:index, :top] do
  	 member do
     get :following, :followers
     end
  end
  resources :relationships, only: [:create, :destroy]
  get '/search' => 'search#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "following_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :follower
  has_many :followers, through: :passive_relationships, source: :following
  attachment :profile_image
  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

   # ユーザーをフォローする
 #followed_idにother_userを追加
  def follow(other_user)
    active_relationships.create(follower_id: other_user.id)
  end

# ユーザーをフォロー解除する
  # followed_idを削除
  def unfollow(other_user)
    active_relationships.find_by(follower_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!,except: [:top]
	 def index
		  @user = current_user

	  	@users = User.all
	  	@book = Book.new
   end

   def create
   	   @user = current_user
		   @books = Book.all
		   @book = Book.new(book_params)
		   @book.user_id = current_user.id
		   if @book.save
		   	flash[:notice] = "Book was successfully created."
		   	redirect_to book_path(@book.id)
		   else
		   	render template: "books/index"
		   end
   end

    def show
		  # @book = Book.find(params[:id]
		  @book = Book.new
		  @user = User.find(params[:id])
		  @books = @user.books
		  #@book =  User.find(params[:id]).books
		  #@books = Book.all.where(user_id: @user.id)
    end

	  def edit
     @user = User.find(params[:id])
       if @user == current_user
     	 else
     	 	@user = current_user
     	  redirect_to user_path(@user.id)
     	 end
    end

    def update
       @user = User.find(params[:id])
  	   if @user.update(user_params)
  	   flash[:notice] = "You have updated user successfully."
  	   redirect_to user_path(@user.id)
       else
       render :edit
       end
    end

     def following
      @user  = User.find(params[:id])
      @users = @user.following
      render 'show_follow'
     end

     def followers
       @user  = User.find(params[:id])
       @users = @user.followers
       render 'show_follower'
     end


    def top
    end

    private

    def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
    end
end

app/helpers/_users_helper.rb
module UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<% unless user == current_user %>
    <% if current_user.following?(user) %>
      <%= render 'relationships/unfollow', user:user %>
    <% else %>
      <%= render 'relationships/follow', user:user %>
    <% end %>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_stats2.html.erb
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー数
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー数
  </a>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= render 'layouts/error_messages', product:@user %>
<%= form_for(@user) do |f| %>
  <div class="form-group has-icon">
    <label class="control-label sr-only" for="inputEmail">Name</label>
    <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
    <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
  </div>
  <div class="form-group has-icon">
  <div class="user-edit-image">
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
  </div>
  <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
</div>
<%= f.text_field :introduction, placeholder:"自己紹介"%>
  <%= f.submit "Update User", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
    <div class="col-xs-3">
<h3>User info</h3>
<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'100x100', class: "img-circle pull-left profile-thumb" %>

<h3>name</h3><h3 class="profile-name"><%= @user.name %></h3>

<h3>introduction</h3><h3 class="profile-introduction"><%= @user.introduction %></h3>

<%= link_to "プロフィール編集", edit_user_path(@user.id) %>
<h3>New book</h3>
<%= form_for(@book) do |f| %>
<%= render 'layouts/error_messages', product: f.object %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_field :body %>
<br><%= f.submit 'Create Book' %></br>

<% end %>
</div>
<div class="col-xs-9">
<h3>Users</h3>
<table class="table">
<thead>
<tr>
<th>image</th>
<th>name</th>
</tr>
</thead>

<tbody>
<% @users.each do |user| %>
<tr>
<td>
<%= link_to user_path(user.id) do %>
<%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'50x50', class: "img-circle pull-left profile-thumb" %>
<% end %>
</td>
<td>
<%= user.name %>
</td>
<td>
フォロー数:<%= user.following.count %>
<td>
フォロワー数:<%= user.followers.count %>
</td>
<td>
<%= render 'users/follow_form', user: user %>
</td>
<td>
<%= link_to "Show", user_path(user.id) %>
</td>
</tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
 <div class="container">
    <div class="row">
    <div class="col-xs-3">
<h3>User info</h3>
<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'100x100', class: "img-circle pull-left profile-thumb" %>
<h3>name</h3><h3 class="profile-name"><%= @user.name %></h3>
<h3>introduction</h3><h3 class="profile-introduction"><%= @user.introduction %></h3>
<section class="stats">
<%= render 'users/stats'%>
</section>
<%= link_to "プロフィール編集", edit_user_path(@user.id) %>
<%= render 'users/follow_form', user:@user %>
<h3>New book</h3>
<%= form_for(@book) do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_field :body %>
<br><%= f.submit 'Create Book' %></br>

<% end %>
</div>
<div class="col-xs-9">

<h3>Books</h3>

<table class="table">
<thead>
<tr>
<th>Title</th>
<th>Opinion</th>
</tr>
</thead>

<tbody>
<% @books.each do |book| %>
<tr>
<td>
<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'50x50', class: "img-circle pull-left profile-thumb" %>
</td>
<td>
<%= link_to book.title, book_path(book.id) %>
</td>
<td>
<%= book.body %>
</td>
</tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/users/show_follow.html.erb
<% @user.following.each do |user| %>
<table class="table">
<tr>
  <td>
  	<%= link_to user_path(user.id) do %>
    <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'50x50', class: "img-circle pull-left profile-thumb" %>
    <% end %>
  </td>
  <td>  <%= user.name %> </td>
  <td>
　　　フォロー数:<%= user.following.count %>
  </td>
  <td>
  	フォロワー数:<%= user.followers.count %>
  </td>
  <td><%= link_to 'Show', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
<table class="table">
<tr>
  <td>
  	<%= link_to user_path(user.id) do %>
    <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'50x50', class: "img-circle pull-left profile-thumb" %>
    <% end %>
  </td>
  <td>  <%= user.name %> </td>
  <td>
　　　フォロー数:<%= user.following.count %>
  </td>
  <td>
  	フォロワー数:<%= user.followers.count %>
  </td>
  <td><%= link_to 'Show', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/top.html.erb
<h1>Welcome Bookers</h1>
<% if user_signed_in? %>
 <%= link_to "Log in",  user_path(current_user.id) %>
 <%= link_to "Sign up", user_path(current_user.id) %>

<% else %>

<%= link_to "Log in", new_user_session_path %>
 <%= link_to "Sign up", new_user_registration_path %>
<% end %>