config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get '/home/about' => 'books#about'
  get  root "users#top"
  devise_for :users
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only:[:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update,:index, :top] do
  	 member do
     get :following, :followers
     end
  end
  resources :relationships, only: [:create, :destroy]
  get '/search' => 'search#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!,except: [:about]

	  def index
		    @user = current_user
	  	  @books = Book.all
	  	  @book = Book.new
    end

      def create
       @user = current_user
  	   @books = Book.all
  	   @book = Book.new(book_params)
  	   @book.user_id = current_user.id
  	   if@book.save
  	   flash[:notice] = "Book was successfully created."
  	   redirect_to book_path(@book.id)
       else
       @books = Book.all
       render :index
       end
      end

     def show
     @book_new = Book.new
  	 @book = Book.find(params[:id])
  	 @user = @book.user
     @book_comment = BookComment.new
     end
     def edit
     	 @book =Book.find(params[:id])
     	 @user = current_user
     	 if @book.user == current_user
     	 else
     	 redirect_to books_path
     	 end
     end

      def update
      #@book = Book.find(params[:id])
      #@book.update(book_params)
      #redirect_to books_path(@book.id)
       @book = Book.find(params[:id])
  	   if @book.update(book_params)
  	   flash[:notice] = "Book was successfully updated."
  	   redirect_to book_path(@book.id)
       else
       render :edit
       end
      end

     def destroy
     	@book = Book.find(params[:id])
     	@book.destroy
     	redirect_to books_path
     end

     def about
     end

     private

     def book_params
     params.require(:book).permit(:title, :body)
     end

end

app/helpers/_books_helper.rb
module BooksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<% book.book_comments.each do |book_comment| %>
      <div class="comment-body bb">
        <div class="comment-avatar">
          <div class="avatar">
           <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'50x50', class: "img-circle pull-left profile-thumb" %>
          </div>
        </div>
        <div class="comment-text">
          <div class="comment-author clearfix">
            <a href="#" class="link-author"><%= book_comment.user.name %></a>
            <span class="comment-meta">
              <span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
            </span>
          </div>
          <div class="comment-entry"><%= book_comment.comment %></div>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true %>
        </div>
      </div>
<% end %>

app/views/books/_favpage.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %>
    <% end %>
<% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true do  %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <%= book.favorites.count %>
    <% end %>
<% end %>

app/views/books/about.html.erb
<h1>Welcome</h1>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
<%= render 'layouts/error_messages', product:@book %>
	<h4>Title</h4>
	<%= f.text_field :title %>
	<h4>本文</h4>
	<%= f.text_area :body %>
	<%= f.submit 'Update Book' %>
<% end %>
<%= link_to "Show",book_path %> | <%= link_to "Back",books_path %>

app/views/books/index.html.erb
<div class="container">
    <div class="row">
    <div class="col-xs-3">
<%= render 'layouts/error_messages', product:@book %>
<h3>User info</h3>
<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'100x100', class: "img-circle pull-left profile-thumb" %>
<h3>name</h3><h3 class="profile-name"><%= @user.name %></h3>
<h3>introduction</h3><h3 class="profile-introduction"><%= @user.introduction %></h3>

<%= link_to "プロフィール編集", edit_user_path(@user.id) %>
<h3>New book</h3>
<%= form_for(@book) do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_field :body %>
<br><%= f.submit 'Create Book' %></br>

<% end %>
</div>
<div class="col-xs-9">
<h3>Books</h3>

<table class="table">
<thead>
<tr>
<th>Title</th>
<th>Opinion</th>
</tr>
</thead>

<tbody>
<% @books.each do |book| %>
<tr>
<td>
<%= link_to user_path(book.user_id) do %>
<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'50x50', class: "img-circle pull-left profile-thumb" %>
<% end %>
</td>
<td>
<%= link_to book.title, book_path(book.id) %>
</td>
<td>
<%= book.body %>
</td>
<td class="book_<%= book.id %>">
 <%= render 'favpage', book: book%>
</td>
<td>
	<p class="comment-count"><%= book.book_comments.count %>件コメント</p>
</td>
<td>
<%= link_to "show", book_path(book.id) %>
</td>
</tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h3>User info</h3>
      <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'100x100', class: "img-circle pull-left profile-thumb" %>
      <h3 class="profile-name"><%= @user.name %></h3>
      <h3 class="profile-introduction"><%= @user.introduction %></h3>
      <%= link_to "プロフィール編集", edit_user_path(@user.id) %>
      <h3>New book</h3>
      <%= form_for(@book_new) do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_field :body %>
        <br><%= f.submit 'Create Book' %></br>
      <% end %>
    </div>
    <div class="col-xs-9">
      <h3>Book detail</h3>
      <table class="table">
        <thead>
          <tr>
          <th></th>
          <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
          <td>
          <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'50x50', class: "img-circle pull-left profile-thumb" %>
          </td>
          <td>
          <%= link_to @user.name, user_path(@user.id) %>
          </td>
          <td>
          <%= @book.title %>
          </td>
          <td>
          <%= @book.body %>
          </td>
          <td>
            <% if @book.user == current_user %>
            <%= link_to "Edit", edit_book_path(@book.id) %>
            <%= link_to "Destroy",book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？" %>
            <% end %>
          </td>
          <td class="book_<%= @book.id %>">
            <%= render 'favpage', book: @book%>
          </td>
          <td>
          	<p class="comment-count"><%= @book.book_comments.count %>件コメント</p>
          </td>
          </tr>
          <td class="book_<%= @book.id %>">
          <%= render 'books/comment', book: @book %>
          </td>
        </tbody>
      </table>
      <%= form_for [@book, @book_comment], remote: true do |f| %>
        <div class="row">
          <div class="col-sm-12">
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
          </div>
        </div>
        <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
      <% end %>
    </div>
  </div>
</div>