config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get '/home/about' => 'books#about'
  get  root "users#top"
  devise_for :users
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only:[:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update,:index, :top] do
  	 member do
     get :following, :followers
     end
  end
  resources :relationships, only: [:create, :destroy]
  get '/search' => 'search#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
    belongs_to :book
    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :following, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "following_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :follower
  has_many :followers, through: :passive_relationships, source: :following
  attachment :profile_image
  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

   # ユーザーをフォローする
 #followed_idにother_userを追加
  def follow(other_user)
    active_relationships.create(follower_id: other_user.id)
  end

# ユーザーをフォロー解除する
  # followed_idを削除
  def unfollow(other_user)
    active_relationships.find_by(follower_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!,except: [:about]

	  def index
		    @user = current_user
	  	  @books = Book.all
	  	  @book = Book.new
    end

      def create
       @user = current_user
  	   @books = Book.all
  	   @book = Book.new(book_params)
  	   @book.user_id = current_user.id
  	   if@book.save
  	   flash[:notice] = "Book was successfully created."
  	   redirect_to book_path(@book.id)
       else
       @books = Book.all
       render :index
       end
      end

     def show
     @book_new = Book.new
  	 @book = Book.find(params[:id])
  	 @user = @book.user
     @book_comment = BookComment.new
     end
     def edit
     	 @book =Book.find(params[:id])
     	 @user = current_user
     	 if @book.user == current_user
     	 else
     	 redirect_to books_path
     	 end
     end

      def update
      #@book = Book.find(params[:id])
      #@book.update(book_params)
      #redirect_to books_path(@book.id)
       @book = Book.find(params[:id])
  	   if @book.update(book_params)
  	   flash[:notice] = "Book was successfully updated."
  	   redirect_to book_path(@book.id)
       else
       render :edit
       end
      end

     def destroy
     	@book = Book.find(params[:id])
     	@book.destroy
     	redirect_to books_path
     end

     def about
     end

     private

     def book_params
     params.require(:book).permit(:title, :body)
     end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
  	@book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
  	@book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
  	@model = params["search"]["model"]
    @content = params["search"]["content"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @content)
   
  end

   private
  def match(model, content)
    if model == 'user'
      User.where(name: content)
    elsif model == 'book'
      Book.where(title: content)
    end
  end

  def forward(model, content)
    if model == 'user'
      User.where("name LIKE ?", "#{content}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{content}%")
    end
  end

  def backward(model, content)
    if model == 'user'
      User.where("name LIKE ?", "%#{content}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{content}")
    end
  end

  def partical(model, content)
    if model == 'user'
      User.where("name LIKE ?", "%#{content}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{content}%")
    end
  end

  def search_for(how, model, content)
    case how
    when 'match'
      match(model, content)
    when 'forward'
      forward(model, content)
    when 'backward'
      backward(model, content)
    when 'partical'
      partical(model, content)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!,except: [:top]
	 def index
		  @user = current_user

	  	@users = User.all
	  	@book = Book.new
   end

   def create
   	   @user = current_user
		   @books = Book.all
		   @book = Book.new(book_params)
		   @book.user_id = current_user.id
		   if @book.save
		   	flash[:notice] = "Book was successfully created."
		   	redirect_to book_path(@book.id)
		   else
		   	render template: "books/index"
		   end
   end

    def show
		  # @book = Book.find(params[:id]
		  @book = Book.new
		  @user = User.find(params[:id])
		  @books = @user.books
		  #@book =  User.find(params[:id]).books
		  #@books = Book.all.where(user_id: @user.id)
    end

	  def edit
     @user = User.find(params[:id])
       if @user == current_user
     	 else
     	 	@user = current_user
     	  redirect_to user_path(@user.id)
     	 end
    end

    def update
       @user = User.find(params[:id])
  	   if @user.update(user_params)
  	   flash[:notice] = "You have updated user successfully."
  	   redirect_to user_path(@user.id)
       else
       render :edit
       end
    end

     def following
      @user  = User.find(params[:id])
      @users = @user.following
      render 'show_follow'
     end

     def followers
       @user  = User.find(params[:id])
       @users = @user.followers
       render 'show_follower'
     end


    def top
    end

    private

    def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
    end
end

app/helpers/_about_helper.rb
module AboutHelper
end

app/helpers/_books_helper.rb
module BooksHelper
end

app/helpers/_users_helper.rb
module UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<header class="navbar navbar-inverse">
  <div class="container-fluid">
    <nav class="navbar-header">
       <h3>Bookers</h3>
    </nav>
      <nav>
      <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
            <li><%= link_to 'Home', user_path(current_user),class: "glyphicon glyphicon-home" %>
            </li>
            <li><%= link_to 'Users', users_path,class: "glyphicon glyphicon-user" %>

            </li>
            <li><%= link_to 'Books', books_path, class: "glyphicon glyphicon-book" %>
            </li>
            <li> <%= link_to "logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out"%>
            </li>

         <% else %>
            <li><%= link_to 'Home', root_path, class: "glyphicon glyphicon-home" %>
          </li>
          <li><%= link_to 'About', home_about_path, class: "glyphicon glyphicon-link" %>
          </li>
          <li>
            <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-pencil" %>
          </li>
          <li>
            <%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in"%>
          </li>

         <% end %>
      </ul>
  </nav>
 </div>
</header>
<% if user_signed_in? %>
    <div class="search-form">
      <%= form_tag(search_path, method: :get) do %>
        <%= text_field_tag 'search[content]' %>
        <%= select_tag 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
        <%= select_tag 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }) %>
        <%= submit_tag '検索', class: "btn btn-primary" %>
      <% end %>
    </div>
  <% end %>
<body>
        <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

        <%= yield %>
  </body>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
</html>